# Generated by Django 5.2.12 on 2026-03-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MelodicTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_note', models.CharField(db_index=True, max_length=10)),
                ('next_note', models.CharField(max_length=10)),
                ('pair_count', models.IntegerField()),
                ('total_occurrences', models.IntegerField()),
                ('probability', models.FloatField()),
            ],
        ),
    ]
